export const news_api = "https://api.voutdoor.ae/api/newsandinsights";
export const product_api = "https://api.voutdoor.ae/api/our-products"
export const home_api = "https://api.voutdoor.ae/api/home";
export const location_points_icons = "https://api.voutdoor.ae/api/our-location-icons";
export const location_points = "https://api.voutdoor.ae/api/our-locations?populate[our_location_icon][populate]=*&pagination[start]=0&pagination[limit]=-1";
export const bublic_url = "https://api.voutdoor.ae/";
export const bublicimage_url = "https://voutdoor.ae/";
export const contactus_api = 'https://api.voutdoor.ae/api/contact-uses';
export const newsletter_api = "https://api.voutdoor.ae/api/newsletters";